os: osx
osx_image: xcode10.2
language: swift
install:
- brew install carthage
- carthage bootstrap
script:
- xcodebuild -configuration Release build
before_deploy:
- git clone https://github.com/jamsinclair/unsign.git
- cd unsign && make 64_ONLY=1 && cd ../
- export APP_NAME=ballast.app
- export ZIP_NAME=ballast-$TRAVIS_BRANCH.zip
- mkdir ./travis-build
- mv ./build/Release/$APP_NAME ./$APP_NAME
# Unsign the built executable to fix "App is Damaged" errors on installation
- "./unsign/unsign ./$APP_NAME/Contents/MacOS/ballast"
- rm ./$APP_NAME/Contents/MacOS/ballast
- mv ./$APP_NAME/Contents/MacOS/ballast.unsigned ./$APP_NAME/Contents/MacOS/ballast
- zip -r ./$ZIP_NAME ./$APP_NAME
- rm -r ./$APP_NAME
deploy:
  provider: releases
  api_key:
    secure: PAlBve7sDxlEFU/j/DROIQ+qFAowb484Q90nRpBRft70zqEGgFoBmWIv12Jq2QsPD1MKK7x0iBJ+HLiF8RYiKvm/mDC+WQ1WCTLkXCrylOi+U23Nq83TOQEZVMdoxF9ozH0oGiRZE0SQFev/smHiOVQp9deEkCU87+gO3dGWjJKuqTeN2VvKPR/0Rb0nuB/vVyR/uZreYPb3Cta4j0oAkvK2utmg08B4fL9dlavfilWLu0WFh4WAD0/VYiox1yKSPUr8CeLaKFtI6EzTE/i9rCuzmqhqtU+0EnzvTSCqyxb46htvRC+H/0pJ+we5fmys7mDfji6NbAUhRNGxFGUQ3FZ0+w/FqpK86bCzGpNL/q6Zyo2zqtPjjLt8j/IW83ZNRNrR+Vq5XCRZEvaNVOVMdaAUI8FpaZg0TrO1XYa5sXCfBY3c1iNb37bo+uM7xBDb2DRmemgt34A6ykucAGMReyTdCOhja4MTop/isHy0mM1r/wJ2+kDqZoXbSJSFQpVKhnICkEA72K+BeGHIuhiravrvcrIwlOKlDS26ozt1OSAj1A4akl+ldsHEJ6eo2zCyetHuig3sOtQOHGCSDuIWv/9KUi/qB3cVz57mEfEfvsCL/vS5vOKoyga/2TwTu9V4K4llVcXPI41yrKvuXC24R0ca7os7Pg/Q3vxJ0L+LcW4=
  file: ./$ZIP_NAME
  skip_cleanup: true
  on:
    repo: jamsinclair/ballast
    branch: master
    tags: true
